from __future__ import annotations

from fqdn_updater.domain.config_schema import ServiceDefinitionConfig, ServiceSourceConfig

_BASE_URL = "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main"

_CATEGORY_KEYS: frozenset[str] = frozenset(
    {
        "anime",
        "block",
        "geoblock",
        "hodca",
        "news",
        "porn",
    }
)

_BLOCK_FILTERS: dict[str, tuple[str, ...]] = {
    "block_p2p_streaming": (
        "1337x.to",
        "anidub.com",
        "annas-archive.org",
        "archiveofourown.org",
        "audiobookbay.lu",
        "babook.org",
        "baginya.org",
        "booktracker.org",
        "bt4gprx.com",
        "btdig.com",
        "cloudtorrents.com",
        "coldfilm.city",
        "coldfilm.ink",
        "coldfilm.xyz",
        "f95-zone.to",
        "fast-torrent.club",
        "filmitorrent.net",
        "filmix.ac",
        "filmix.biz",
        "filmix.day",
        "filmix.fan",
        "filmix.fm",
        "filmix.la",
        "flibusta.is",
        "flibusta.net",
        "flisland.net",
        "gamesrepack.com",
        "hdkinoteatr.com",
        "hdstudio.org",
        "ilook.tv",
        "iptv.online",
        "kino.pub",
        "kinogo.ec",
        "kinogo.uk",
        "kinopub.me",
        "kinovod.net",
        "kinozal.guru",
        "kinozal.me",
        "kinozal.tv",
        "kinozaltv.life",
        "le-production.tv",
        "lib.rus.ec",
        "libgen.li",
        "livetv.sx",
        "lostfilm.download",
        "lostfilm.tv",
        "lostfilm.tw",
        "lostfilm.uno",
        "lostfilmtv2.site",
        "lostfilm.top",
        "megapeer.ru",
        "megapeer.vip",
        "nnmclub.to",
        "nnmstatic.win",
        "opentrackr.org",
        "piratbit.top",
        "render-state.to",
        "riperam.org",
        "rustorka.com",
        "rutor.info",
        "rutor.is",
        "rutor.org",
        "rutracker.cc",
        "rutracker.net",
        "rutracker.org",
        "rutracker.wiki",
        "sci-hub.se",
        "sci-hub.st",
        "seasonvar.ru",
        "selezen.org",
        "shiza-project.com",
        "thepiratebay.org",
        "thetvdb.com",
        "turbobit.net",
        "twirpx.com",
        "zbigz.com",
    ),
    "block_vpn_proxy_privacy": (
        "10minutemail.com",
        "5sim.net",
        "amnezia.org",
        "archive.ph",
        "censortracker.org",
        "cock.li",
        "croxyproxy.com",
        "cyberghostvpn.com",
        "getoutline.org",
        "lantern.io",
        "mailfence.com",
        "mailo.com",
        "mullvad.net",
        "onlinesim.io",
        "psiphon.ca",
        "proton.me",
        "protonvpn.com",
        "redshieldvpn.com",
        "riseup.net",
        "signal.org",
        "simplex.chat",
        "simplex.im",
        "skiff.com",
        "sms-activate.io",
        "startmail.com",
        "startpage.com",
        "surfshark.com",
        "threema.ch",
        "tiptop-vpn.com",
        "torproject.org",
        "tuta.com",
        "tuta.io",
        "viber.com",
        "vpngate.net",
        "vpngen.org",
        "vpnlove.me",
        "vpnpay.io",
    ),
    "block_dev_hosting_security": (
        "adguard.com",
        "adminforge.de",
        "ahrefs.com",
        "avira.com",
        "bluehost.com",
        "bufferbloat.net",
        "codelinaro.org",
        "designify.com",
        "digikey.com",
        "digitalocean.com",
        "dreamhost.com",
        "dub.sh",
        "edu-cisco.org",
        "element14.com",
        "elements.envato.com",
        "git.new",
        "godaddy.com",
        "gonitro.com",
        "hackernoon.com",
        "hackmd.io",
        "hetzner.com",
        "hostgator.com",
        "infineon.com",
        "ionos.com",
        "kamatera.com",
        "kilo.ai",
        "kilocode.ai",
        "leafletjs.com",
        "linear.app",
        "lucid.app",
        "malwarebytes.com",
        "monolisa.dev",
        "networksolutions.com",
        "notepad-plus-plus.org",
        "omv-extras.org",
        "pages.dev",
        "primevue.org",
        "refactoring.guru",
        "sap.com",
        "scrollrevealjs.org",
        "showip.net",
        "sophos.com",
        "speedtest.net",
        "statology.org",
        "trellix.com",
        "zendesk.com",
    ),
    "block_finance_shopping": (
        "allegro.pl",
        "bestchange.ru",
        "coinpayments.net",
        "coinsbee.com",
        "interactivebrokers.co.uk",
        "kupujemprodajem.com",
        "okx.com",
        "olx.ua",
        "opensea.io",
        "polymarket.com",
        "privatekeys.pw",
        "temu.com",
    ),
    "block_social_creators": (
        "7tv.app",
        "7tv.io",
        "bcbits.com",
        "booth.pm",
        "pximg.net",
        "charhub.io",
        "chess.com",
        "chesscomfiles.com",
        "chub.ai",
        "deviantart.com",
        "epidemz.net.co",
        "everand.com",
        "flipboard.com",
        "gamedistribution.com",
        "goodreads.com",
        "gr-assets.com",
        "ign.com",
        "itch.io",
        "knowyourmeme.com",
        "kym-cdn.com",
        "licdn.com",
        "linkedin.com",
        "linktr.ee",
        "mashable.com",
        "medium.com",
        "metal-archives.com",
        "modrinth.com",
        "more.fm",
        "musicbrainz.org",
        "musixmatch.com",
        "nhl.com",
        "patreon.com",
        "patreonusercontent.com",
        "pixabay.com",
        "pixiv.net",
        "prnt.sc",
        "pronouns.page",
        "quora.com",
        "quora.com.cdn.cloudflare.net",
        "radiojar.com",
        "rentry.co",
        "restream.io",
        "sndcdn.com",
        "soundcloud.cloud",
        "soundcloud.com",
        "spreadthesign.com",
        "steamstat.info",
        "trueblackmetalradio.com",
        "unsplash.com",
        "vice.com",
        "visualcapitalist.com",
        "webmd.com",
        "webtoons.com",
        "fextralife.com",
        "x-minus.pro",
    ),
    "block_news_politics": (
        "4freerussia.org",
        "abook-club.ru",
        "botnadzor.org",
        "carnegieendowment.org",
        "deepstatemap.live",
        "dpidetector.org",
        "freedomletters.org",
        "gagadget.com",
        "iditelesombase.org",
        "iedb.org",
        "jw-russia.org",
        "jw.org",
        "knews.kg",
        "liveuamap.com",
        "navalny.com",
        "neformat.com.ua",
        "nih.gov",
        "nippon.com",
        "opensanctions.org",
        "rublacklist.net",
        "saverudata.net",
        "swissinfo.ch",
        "ukr.net",
        "ukrtelcdn.net",
        "wilsoncenter.org",
    ),
}
_BLOCK_FILTER_KEYS: tuple[str, ...] = tuple(_BLOCK_FILTERS)
_BLOCK_FILTER_SUFFIXES: tuple[str, ...] = tuple(
    sorted({suffix for suffixes in _BLOCK_FILTERS.values() for suffix in suffixes})
)

_GEOBLOCK_FILTERS: dict[str, tuple[str, ...]] = {
    "geoblock_ai": (
        "ai.com",
        "ai-chat.bsg.brave.com",
        "anthropic.com",
        "anthropic.qualtrics.com",
        "api.jetbrains.ai",
        "augmentcode.com",
        "chat.com",
        "chat.openai.com.cdn.cloudflare.net",
        "chatgpt.com",
        "claude.ai",
        "claude.com",
        "clip.opus.pro",
        "codeium.com",
        "copilot.microsoft.com",
        "deepl.com",
        "designer.microsoft.com",
        "diabrowser.com",
        "elevenlabs.io",
        "files.manus.cdn",
        "genspark.ai",
        "grok.com",
        "grok.x.com",
        "groq.com",
        "hume.ai",
        "kaleido.ai",
        "lambdalabs.com",
        "langdock.com",
        "lightning.ai",
        "manus.im",
        "oaistatic.com",
        "oaiusercontent.com",
        "openai.com",
        "openrouter.ai",
        "proactivebackend-pa.googleapis.com",
        "production-openaicom-storage.azureedge.net",
        "qodana.cloud",
        "qoder.com",
        "recraft.ai",
        "remove.bg",
        "reve.art",
        "sonara.ai",
        "sora.com",
        "trae.ai",
        "uizard.io",
        "unscreen.com",
        "watermarkremover.io",
        "windsurf.com",
        "x.ai",
    ),
    "geoblock_dev_cloud_saas": (
        "amplitude.com",
        "atlassian.com",
        "bitnami.com",
        "buf.build",
        "capacitorjs.com",
        "citrix.com",
        "clickup.com",
        "code.gist.build",
        "connect.ngrok-agent.com",
        "dashboard.algolia.com",
        "dashboard.gitguardian.com",
        "data.cline.bot",
        "document360.com",
        "document360.io",
        "editorx.com",
        "fivetran.com",
        "flourish.studio",
        "force-user-content.com",
        "force.com",
        "framer.com",
        "grafana.com",
        "graylog.org",
        "hashicorp.com",
        "hc-ping.com",
        "hchk.io",
        "heroku.com",
        "herokucdn.com",
        "htmhell.dev",
        "httptoolkit.com",
        "intercom.io",
        "jetbrains.com",
        "jetbrains.space",
        "liquibase.com",
        "mailerlite.com",
        "mattermost.com",
        "middlewareinventory.com",
        "mongodb.com",
        "myjetbrains.com",
        "neo4j.com",
        "netlify.com",
        "ngrok.com",
        "notion.com",
        "notion.new",
        "notion.site",
        "notion.so",
        "notion-static.com",
        "notion-emojis.s3-us-west-2.amazonaws.com",
        "octopus.do",
        "onshape.com",
        "oraclecloud.com",
        "pingdom.com",
        "platform.activestate.com",
        "posthog.com",
        "qwant.com",
        "reactflow.dev",
        "redis.io",
        "redislabs.com",
        "research.net",
        "salesforce-experience.com",
        "salesforce-hub.com",
        "salesforce-scrt.com",
        "salesforce-setup.com",
        "salesforce-sites.com",
        "salesforce.com",
        "salesforceiq.com",
        "salesforceliveagent.com",
        "semrush.com",
        "sentry.dev",
        "sentry.io",
        "servarr.com",
        "site.com",
        "siteground.com",
        "smartbear.co",
        "smartbear.com",
        "snyk.io",
        "spacelift.io",
        "surveymonkey.com",
        "swagger.io",
        "terraform.io",
        "toolbox.app",
        "vagrantcloud.com",
        "weebly.com",
        "wetransfer.com",
        "wpengine.com",
        "youtrack.cloud",
        "zapier.com",
    ),
    "geoblock_media_games": (
        "a-vrv.akamaized.net",
        "alphacoders.com",
        "brawlstarsgame.com",
        "cdromance.org",
        "clashofclans.com",
        "clashroyaleapp.com",
        "crunchyroll.com",
        "crunchyrollcdn.com",
        "deezer.com",
        "digitalcontent.sky",
        "disneyplus.com",
        "f1.com",
        "fast.com",
        "footballapi.pulselive.com",
        "formula1.com",
        "fxnetworks.com",
        "geforcenow.com",
        "gfn.am",
        "global.fncstatic.com",
        "gql.twitch.tv",
        "guilded.gg",
        "haydaygame.com",
        "hbomax.com",
        "image.tmdb.org",
        "kinogo.la",
        "last.fm",
        "lidarr.audio",
        "marvelsnap.com",
        "max.com",
        "metopera.org",
        "mixcloud.com",
        "nba.com",
        "netflix.ca",
        "netflix.com",
        "netflix.net",
        "netflixinvestor.com",
        "netflixtechblog.com",
        "nfl.com",
        "nflxext.com",
        "nflximg.com",
        "nflximg.net",
        "nflxsearch.net",
        "nflxso.net",
        "nflxvideo.net",
        "pcgamesn.com",
        "philiascans.org",
        "premierleague.com",
        "primevideo.com",
        "prowlarr.com",
        "public.parsec.app",
        "builds.parsec.app",
        "sky.com",
        "skycdp.com",
        "snapgametech.com",
        "spotify.com",
        "squadbustersgame.com",
        "streamable.com",
        "supercell.com",
        "theaudiodb.com",
        "themoviedb.org",
        "tidal.com",
        "tmdb-image-prod.b-cdn.net",
        "tmdb.com",
        "tmdb.org",
        "torrenteditor.com",
        "usher.ttvnw.net",
        "v.vrv.co",
        "vod-fy.crunchyrollcdn.com",
        "wbagora.com",
        "wbgames.com",
        "widgetapp.stream",
        "x-minus.pro",
        "xsts.auth.xboxlive.com",
        "zedge.net",
    ),
    "geoblock_shopping_travel": (
        "abercrombie.com",
        "adidas.com",
        "aircanada.com",
        "alza.hu",
        "amazon.com",
        "bestbuy.com",
        "btod.com",
        "buymeacoffee.com",
        "carrefouruae.com",
        "cdw.com",
        "chainreactioncycles.com",
        "disctech.com",
        "ducati.com",
        "dyson.com",
        "eneba.com",
        "etsy.com",
        "g2a.com",
        "gameloft.com",
        "gamestop.com",
        "gaming.amazon.com",
        "glpals.com",
        "gonift.com",
        "groupon.com",
        "hollisterco.com",
        "home.by.me",
        "hotels.com",
        "ikea.com",
        "iherb.com",
        "klarna.com",
        "lyst.com",
        "mintmobile.com",
        "monoprice.com",
        "newark.com",
        "nike.com",
        "ocstore.com",
        "primark.com",
        "sephora.com",
        "shop.gameloft.com",
        "techbargains.com",
        "timberland.de",
        "uaudio.com",
        "upwork.com",
        "volkswagen-classic-parts.com",
        "walmart.com",
        "webnames.ca",
        "xiaomi.eu",
        "yeggi.com",
    ),
    "geoblock_enterprise_hardware": (
        "adobe.com",
        "adobe.io",
        "adobe.net",
        "affinity.studio",
        "analog.com",
        "ansys.com",
        "arduino.cc",
        "autodesk.com",
        "bell-sw.com",
        "bosch.com",
        "boschaftermarket.com",
        "boschautoparts.com",
        "broadcom.com",
        "canva.com",
        "canva.dev",
        "chaos.com",
        "cisco.com",
        "contabo.com",
        "corsair.com",
        "cpu-monkey.com",
        "daemon-tools.cc",
        "dell.com",
        "dellcdn.com",
        "devexpress.com",
        "expandrive.com",
        "flir.com",
        "flir.eu",
        "fluke.com",
        "flukenetworks.com",
        "gpu-monkey.com",
        "home-connect.com",
        "hostinger.com",
        "ibm.com",
        "intel.com",
        "intel.de",
        "intel.nl",
        "jamf.com",
        "keysight.com",
        "lgeapi.com",
        "lgthinq.com",
        "mouser.com",
        "mouser.fi",
        "multisim.com",
        "myparallels.com",
        "netacad.com",
        "netapp.com",
        "new.abb.com",
        "ni.com",
        "nitropdf.com",
        "nvidia.com",
        "nxp.com",
        "omnissa.com",
        "oracle.com",
        "parallels.cn",
        "parallels.com",
        "parallels.net",
        "parallelsaccess.com",
        "qt.io",
        "qualcomm.com",
        "schneider-electric.com",
        "sdxcentral.com",
        "se.com",
        "sketchup.com",
        "smartdeploy.com",
        "snapgene.com",
        "solarwinds.com",
        "spiceworks.com",
        "tableau.com",
        "ti.com",
        "trailblazer.me",
        "trailhead.com",
        "tsmc.com",
        "veeam.com",
        "verificationacademy.com",
        "vmware.com",
        "xrite.com",
        "xerox.com",
    ),
    "geoblock_security_networking": (
        "app.zerossl.com",
        "bitdefender.com",
        "clamav.net",
        "cisecurity.org",
        "community.sophos.com",
        "cvedetails.com",
        "data-cdn.mbamupdates.com",
        "easydmarc.com",
        "geolocation.onetrust.com",
        "hybrid-analysis.com",
        "intelix.sophos.com",
        "joesandbox.com",
        "nordaccount.com",
        "nordcdn.com",
        "nordvpn.com",
        "openh264.org",
        "pandasecurity.com",
        "pkgs.tailscale.com",
        "remna.st",
        "snort.org",
        "support.anydesk.com",
        "talosintelligence.com",
        "teamviewer.com",
        "tria.ge",
        "tutanota.com",
        "vyos.io",
        "watchguard.com",
        "zerossl.com",
    ),
    "geoblock_finance_payments": (
        "coingate.com",
        "exchanger.bits.media",
        "gofund.me",
        "gofundme.com",
        "intuit.com",
        "intuitibits.com",
        "onfastspring.com",
        "paddle.com",
        "paddlestatus.com",
        "paritydeals.com",
        "profitwell.com",
        "quicknode.com",
        "squareup.com",
        "transferwise.com",
        "wise.com",
    ),
    "geoblock_health_reference": (
        "akc.org",
        "all3dp.com",
        "cats.com",
        "clevelandclinic.org",
        "credly.com",
        "extremetech.com",
        "habr.com",
        "healthline.com",
        "ldoceonline.com",
        "lifehacker.com",
        "manybooks.net",
        "medicalnewstoday.com",
        "myheritage.com",
        "news.google.com",
        "pcmag.com",
        "penguin.com",
        "penguinrandomhouse.com",
        "typing.com",
        "weather.com",
        "wikidot.com",
        "wunderground.com",
    ),
}
_GEOBLOCK_FILTER_KEYS: tuple[str, ...] = tuple(_GEOBLOCK_FILTERS)
_GEOBLOCK_FILTER_SUFFIXES: tuple[str, ...] = tuple(
    sorted({suffix for suffixes in _GEOBLOCK_FILTERS.values() for suffix in suffixes})
)

_HODCA_FILTERS: dict[str, tuple[str, ...]] = {
    "hodca_dev_cloud_saas": (
        "bitbucket.org",
        "clerk.com",
        "clerk.dev",
        "coderabbit.ai",
        "discourse-cdn.com",
        "galaxy.ansible.com",
        "grafana.net",
        "hetzner.com",
        "hetzner.cloud",
        "hostero.eu",
        "lifeforge.dev",
        "litellm.ai",
        "llhost.eu",
        "mongodb.com",
        "nuxt.com",
        "opencode.ai",
        "opentext.com",
        "patterns.dev",
        "pinata.cloud",
        "pinia-colada.esm.dev",
        "plantuml.com",
        "porkbun.com",
        "pstmn.io",
        "pypi.org",
        "redux.js.org",
        "strapi.io",
        "storybook.js.org",
        "tailwind-variants.org",
        "tiny.cloud",
        "utils.docs.rw",
        "yarnpkg.com",
    ),
    "hodca_network_os_tools": (
        "3os.org",
        "adbappcontrol.com",
        "archlinux.org",
        "armbian.com",
        "armbian.de",
        "artixlinux.org",
        "check-host.net",
        "clashverge.dev",
        "cloudflare.com",
        "cloudns.net",
        "crdroid.net",
        "desec.io",
        "fedoraproject.org",
        "flathub.org",
        "flclash.cc",
        "fosshub.com",
        "fwupd.org",
        "gnome.org",
        "heltec.org",
        "imazing.com",
        "iot334.com",
        "ipinfo.app",
        "izzysoft.de",
        "karing.app",
        "kde.org",
        "linuxserver.io",
        "localsend.org",
        "luadns.com",
        "manjaro.org",
        "meshtastic.org",
        "mirror.chaotic.cx",
        "netbird.io",
        "nextcloud.com",
        "nixos.org",
        "one.one.one.one",
        "openwrt.org",
        "ovh.ie",
        "protonvpn.com",
        "silabs.com",
        "sing-box.sagernet.org",
        "snikket.org",
        "teamviewer.com",
        "tuya-inc.cn",
        "tuya.com",
        "tuyaaf.com",
        "tuyacn.com",
        "tuyaeu.com",
        "tuyain.com",
        "tuyaus.com",
        "ubuntu-touch.io",
        "windowsupdate.com",
        "xraycore.org",
        "zerotier.com",
    ),
    "hodca_media_games": (
        "acclaimedvideogames.com",
        "alterportal.net",
        "aniliberty.top",
        "artstation.com",
        "beatsaver.com",
        "beatmods.com",
        "beamng.com",
        "bsmanager.io",
        "capcut.com",
        "capcutapi.com",
        "capcutstatic.com",
        "capcutvod.com",
        "clubtv.pro",
        "curseforge.com",
        "discogs.com",
        "eaaccounts.akamaized.net",
        "fandom.com",
        "fastpic.org",
        "filmix.my",
        "heavyfetish.com",
        "ixxx.com",
        "jellyfin.org",
        "jinxxy.com",
        "libria.fun",
        "mediafilez.forgecdn.net",
        "music.apple.com",
        "nexusmods.com",
        "nintendo.com",
        "opensubtitles.org",
        "polyhaven.com",
        "protondb.com",
        "resizing.flixster.com",
        "rottentomatoes.com",
        "rulet.tv",
        "rutracker.org",
        "sb-cd.com",
        "smods.ru",
        "spankbang.com",
        "sxyprn.com",
        "sxyprn.net",
        "trueachievements.com",
        "tunemymusic.com",
        "vod.streamgum.com",
        "vrchat.cloud",
        "vrchat.com",
        "wbgames.com",
    ),
    "hodca_ai_education_research": (
        "britishcouncil.org",
        "cdn-lfs-eu-1.hf.co",
        "cdn-lfs-us-1.hf.co",
        "cdn-lfs.hf.co",
        "cdn-lfs.huggingface.co",
        "cochrane.org",
        "edx.org",
        "elsevier.com",
        "elsevier.com.cdn.cloudflare.net",
        "huggingface.co",
        "imigo.ai",
        "lenso.ai",
        "mdpi.com",
        "scira.ai",
        "skillsforall.com",
        "tefl.org",
        "thelancet.com",
    ),
    "hodca_social_lifestyle": (
        "ajay.app",
        "cdn.embedly.com",
        "dev.to",
        "dosvid.tk",
        "feeds.feedburner.com",
        "forum.syncthing.net",
        "gopro.com",
        "howtogeek.com",
        "imgbb.com",
        "inoreader.com",
        "memepedia.ru",
        "openrailwaymap.org",
        "pinterest.com",
        "reddit.com",
        "static.wixstatic.com",
        "strava.com",
        "xda-developers.com",
        "xdaforums.com",
    ),
    "hodca_finance_shopping": (
        "amazon.com",
        "amazonaws.com",
        "dockhand.pro",
        "dodopayments.com",
        "drpool.io",
        "htx.com",
        "ikea.com",
        "nextdirect.com",
        "qualtrics.com",
        "russianfood.com",
        "stripe.com",
        "stripecdn.com",
        "tremendous.com",
        "youngliving.com",
    ),
}
_HODCA_FILTER_KEYS: tuple[str, ...] = tuple(_HODCA_FILTERS)
_HODCA_FILTER_SUFFIXES: tuple[str, ...] = tuple(
    sorted({suffix for suffixes in _HODCA_FILTERS.values() for suffix in suffixes})
)

_SERVICE_KEYS: tuple[str, ...] = (
    "anime",
    "block",
    *_BLOCK_FILTER_KEYS,
    "block_other",
    "geoblock",
    *_GEOBLOCK_FILTER_KEYS,
    "geoblock_other",
    "hodca",
    *_HODCA_FILTER_KEYS,
    "hodca_other",
    "news",
    "porn",
    "cloudflare",
    "cloudfront",
    "digitalocean",
    "discord",
    "google_ai",
    "google_meet",
    "google_play",
    "hdrezka",
    "hetzner",
    "meta",
    "ovh",
    "roblox",
    "telegram",
    "tiktok",
    "twitter",
    "youtube",
)

_SERVICE_DESCRIPTIONS: dict[str, str] = {
    "anime": "Anime category domains from itdoginfo/allow-domains.",
    "block": "Blocked category domains from itdoginfo/allow-domains.",
    "block_p2p_streaming": "P2P, streaming mirrors, and piracy-related domains from block.",
    "block_vpn_proxy_privacy": "VPN, proxy, privacy, and temporary identity domains from block.",
    "block_dev_hosting_security": "Developer, hosting, DNS, and security tool domains from block.",
    "block_finance_shopping": "Finance, crypto, marketplace, and shopping domains from block.",
    "block_social_creators": "Social, creator, community, and media domains from block.",
    "block_news_politics": "News, politics, public-interest, and civil-society domains from block.",
    "block_other": "Block category domains not covered by the focused block sublists.",
    "geoblock": "GeoBlock category domains from itdoginfo/allow-domains.",
    "geoblock_ai": "AI assistants, model providers, and AI tooling domains from geoblock.",
    "geoblock_dev_cloud_saas": "Developer, cloud, SaaS, and productivity domains from geoblock.",
    "geoblock_media_games": "Streaming, games, sports, and entertainment domains from geoblock.",
    "geoblock_shopping_travel": "Shopping, travel, and consumer brand domains from geoblock.",
    "geoblock_enterprise_hardware": "Enterprise software and hardware domains from geoblock.",
    "geoblock_security_networking": "Security, networking, and VPN domains from geoblock.",
    "geoblock_finance_payments": "Payments, finance, and billing domains from geoblock.",
    "geoblock_health_reference": "Health, reference, education, and news domains from geoblock.",
    "geoblock_other": "GeoBlock category domains not covered by the focused geoblock sublists.",
    "hodca": "H.O.D.C.A category domains from itdoginfo/allow-domains.",
    "hodca_dev_cloud_saas": "Developer, cloud, SaaS, and hosting domains from H.O.D.C.A.",
    "hodca_network_os_tools": "Network, OS, device, and utility domains from H.O.D.C.A.",
    "hodca_media_games": "Media, games, mods, and entertainment domains from H.O.D.C.A.",
    "hodca_ai_education_research": "AI, education, and research domains from H.O.D.C.A.",
    "hodca_social_lifestyle": "Social, community, travel, and lifestyle domains from H.O.D.C.A.",
    "hodca_finance_shopping": (
        "Finance, payments, shopping, and marketplace domains from H.O.D.C.A."
    ),
    "hodca_other": "H.O.D.C.A domains not covered by focused H.O.D.C.A sublists.",
    "news": "Blocked news domains from itdoginfo/allow-domains.",
    "porn": "Porn category domains from itdoginfo/allow-domains.",
    "cloudflare": "Cloudflare domains and subnets from itdoginfo/allow-domains.",
    "cloudfront": "CloudFront domains and subnets from itdoginfo/allow-domains.",
    "digitalocean": "DigitalOcean domains and subnets from itdoginfo/allow-domains.",
    "discord": "Discord domains and subnets from itdoginfo/allow-domains.",
    "google_ai": "Dedicated Google AI domains from itdoginfo/allow-domains.",
    "google_meet": "Google Meet domains and subnets from itdoginfo/allow-domains.",
    "google_play": "Google Play domains from itdoginfo/allow-domains.",
    "hdrezka": "HDRezka domains from itdoginfo/allow-domains.",
    "hetzner": "Hetzner domains and subnets from itdoginfo/allow-domains.",
    "meta": "Meta family domains and subnets from itdoginfo/allow-domains.",
    "ovh": "OVH domains and subnets from itdoginfo/allow-domains.",
    "roblox": "Roblox domains and IPv4 subnets from itdoginfo/allow-domains.",
    "telegram": "Telegram domains and subnets from itdoginfo/allow-domains.",
    "tiktok": "TikTok domains from itdoginfo/allow-domains.",
    "twitter": "Twitter and X domains and subnets from itdoginfo/allow-domains.",
    "youtube": "YouTube domains from itdoginfo/allow-domains.",
}

_IPV4_SUBNET_SERVICE_KEYS: frozenset[str] = frozenset(
    {
        "cloudflare",
        "cloudfront",
        "digitalocean",
        "discord",
        "google_meet",
        "hetzner",
        "meta",
        "ovh",
        "roblox",
        "telegram",
        "twitter",
    }
)
_IPV6_SUBNET_SERVICE_KEYS: frozenset[str] = _IPV4_SUBNET_SERVICE_KEYS - {"roblox"}


def _service_definition(key: str) -> ServiceDefinitionConfig:
    if key in _BLOCK_FILTERS:
        return _filtered_category_definition(
            key=key,
            category_key="block",
            include_domain_suffixes=_BLOCK_FILTERS[key],
        )
    if key == "block_other":
        return _filtered_category_definition(
            key=key,
            category_key="block",
            exclude_domain_suffixes=_BLOCK_FILTER_SUFFIXES,
        )
    if key in _GEOBLOCK_FILTERS:
        return _filtered_category_definition(
            key=key,
            category_key="geoblock",
            include_domain_suffixes=_GEOBLOCK_FILTERS[key],
        )
    if key == "geoblock_other":
        return _filtered_category_definition(
            key=key,
            category_key="geoblock",
            exclude_domain_suffixes=_GEOBLOCK_FILTER_SUFFIXES,
        )
    if key in _HODCA_FILTERS:
        return _filtered_category_definition(
            key=key,
            category_key="hodca",
            include_domain_suffixes=_HODCA_FILTERS[key],
        )
    if key == "hodca_other":
        return _filtered_category_definition(
            key=key,
            category_key="hodca",
            exclude_domain_suffixes=_HODCA_FILTER_SUFFIXES,
        )
    if key in _CATEGORY_KEYS:
        return ServiceDefinitionConfig(
            key=key,
            source_urls=[f"{_BASE_URL}/Categories/{key}.lst"],
            format="raw_domain_list",
            description=_SERVICE_DESCRIPTIONS[key],
        )

    sources = [
        ServiceSourceConfig(
            url=f"{_BASE_URL}/Services/{key}.lst",
            format="raw_domain_list",
        )
    ]
    if key in _IPV4_SUBNET_SERVICE_KEYS:
        sources.append(
            ServiceSourceConfig(
                url=f"{_BASE_URL}/Subnets/IPv4/{key}.lst",
                format="raw_cidr_list",
            )
        )
    if key in _IPV6_SUBNET_SERVICE_KEYS:
        sources.append(
            ServiceSourceConfig(
                url=f"{_BASE_URL}/Subnets/IPv6/{key}.lst",
                format="raw_cidr_list",
            )
        )

    return ServiceDefinitionConfig(
        key=key,
        sources=sources,
        description=_SERVICE_DESCRIPTIONS[key],
    )


def _filtered_category_definition(
    *,
    key: str,
    category_key: str,
    include_domain_suffixes: tuple[str, ...] = (),
    exclude_domain_suffixes: tuple[str, ...] = (),
) -> ServiceDefinitionConfig:
    return ServiceDefinitionConfig(
        key=key,
        sources=[
            ServiceSourceConfig(
                url=f"{_BASE_URL}/Categories/{category_key}.lst",
                format="raw_domain_list",
                include_domain_suffixes=list(include_domain_suffixes),
                exclude_domain_suffixes=list(exclude_domain_suffixes),
            )
        ],
        description=_SERVICE_DESCRIPTIONS[key],
    )


def builtin_service_definitions() -> list[ServiceDefinitionConfig]:
    """Return built-in source definitions used for scaffold config generation."""

    return [_service_definition(key) for key in _SERVICE_KEYS]
